### ISSUE TITLE
Change get_recommendation_by_movie_name to get_recommendation_by_movie_id in Cache

### ISSUE THREAD

**Issue by SN-18** [pncnmnp/SE21-project#26]
If we store movie recommendations by movie name, it's possible to poison the cache for cases where two movies with the same name exists. For example: "the avengers" is the movie name of two movies, one from 1998 and another from 2012, this would result in storing recommendations just for one of these movies and giving the same recommendations for both the movies because cache doesn't store recommendations by id, it stores them by name.

**Comment by rdeodha** [comment]
This has been fixed, movie_id is now used instead of movie_name.
