### ISSUE TITLE
get_recommendation_by_movie should accept movie_id instead of Movie object

### ISSUE THREAD

**Issue by SN-18** [pncnmnp/SE21-project#28]
Function recommend_movie (in app.py) would receive movie_id from the frontend UI instead of movie_name, this can be passed directly to the get_recommendation_by_movie (from app.py to tmdb.py) function for getting the movies recommendations.

Right now get_recommendation_by_movie accepts Movie object and to convert movie_id into object, it either needs to be passed through the UI to recommend_movie function or requires a back-end call to get_movies_from_query_string, which are both unnecessary and complicated. We should change the get_recommendation_by_movie's parameter type from movie object to int, for movie_id.

**Comment by rdeodha** [comment]
Issue has been resolved, function uses movie_id instead of movie_name.
